
services:
  db:
    image: mysql:8.0
    ports:
      - 3308:3308
    environment:
      MYSQL_DATABASE: fc_clubs
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database/mysql/data:/var/lib/mysql
    networks:
      - app

  web:
    build:
      dockerfile: ./docker/Dockerfile
      context: ./
    command: ./wait-for-it.sh db:3306 -- ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/fc_clubs
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
    networks:
      - app
    environment:
      PYTHONUNBUFFERED: 1

networks:
  app:
    driver: bridge