
services:
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/home/app/web
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - app

  db:
    image: mysql:8.0
    ports:
      - 3308:3308
    environment:
      MYSQL_DATABASE: fc_clubs
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database/mysql/data:/var/lib/mysql
    networks:
      - app

  web:
    build:
      dockerfile: ./docker/Dockerfile
      context: ./
    command: gunicorn fc_clubs.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/fc_clubs
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
    networks:
      - app
    environment:
      PYTHONUNBUFFERED: 1

networks:
  app:
    driver: bridge