# Generated by Django 5.1.7 on 2025-03-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
