# Generated by Django 5.1.7 on 2025-03-25 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_club_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='url',
        ),
    ]
