# Generated by Django 5.1.7 on 2025-03-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_club_approved_club_approved_by_club_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='display_on_main_page',
            field=models.BooleanField(default=False),
        ),
    ]
