# Generated by Django 5.1.7 on 2025-03-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_club_display_on_main_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='since_year',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
