# Generated by Django 5.1.7 on 2025-03-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_club_description_club_since_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='site_page',
            field=models.URLField(max_length=256, null=True),
        ),
    ]
