# Generated by Django 5.1.7 on 2025-03-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_club_site_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='img_emblem',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='club',
            name='since_year',
            field=models.IntegerField(null=True),
        ),
    ]
