# Generated by Django 5.1.7 on 2025-05-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_alter_club_img_emblem'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('clubs', models.ManyToManyField(to='clubs.club')),
            ],
        ),
    ]
