# Generated by Django 5.1.7 on 2025-05-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='clubs',
        ),
    ]
