# Generated by Django 5.1.7 on 2025-05-10 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_remove_league_clubs'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.club')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.league')),
            ],
        ),
    ]
