# Generated by Django 5.1.7 on 2025-05-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_leagueclub'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='description',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='img_emblem',
            field=models.ImageField(blank=True, default='league/images/Default_image.png', upload_to='league/images/'),
        ),
        migrations.AlterField(
            model_name='league',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
