# Generated by Django 5.1.7 on 2025-03-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='display_on_main_page',
            field=models.BooleanField(default=False),
        ),
    ]
