# Generated by Django 5.1.7 on 2025-03-31 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_club_img_emblem'),
        ('players', '0003_player_display_on_main_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='club',
        ),
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
    ]
