# Generated by Django 5.1.7 on 2025-05-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_remove_player_club_player_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, default='players/images/Default_player.jpg', upload_to='players/images/'),
        ),
    ]
