# Generated by Django 5.1.7 on 2025-05-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_alter_player_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, default='players/images/Default_player.png', upload_to='players/images/'),
        ),
    ]
